### ISSUE TITLE
Stray semicolon in Loadout macros

### ISSUE THREAD

**Issue by dedmen** [xrufix/ZGM#2]
https://github.com/xrufix/ZGM/blob/fdb5d2d523b435ba74a087243b526bf66f7fe8ff/xru_ZGM/loadouts/factions/FANB.hpp#L187
https://github.com/xrufix/ZGM/blob/ceb79881e59481dc7f2ddbb3404e5e3cb00acbfa/xru_ZGM/loadouts/factions/BW_FLECK.hpp#L190
https://github.com/xrufix/ZGM/blob/fdb5d2d523b435ba74a087243b526bf66f7fe8ff/xru_ZGM/loadouts/factions/USMC_D.hpp#L240
https://github.com/xrufix/ZGM/blob/7329fa38fc10ed16027bf9fc8039e68c958cdd3c/xru_ZGM/loadouts/factions/USARMY_OCP.hpp#L240
have semicolon at the end.
https://github.com/xrufix/ZGM/search?q=G_Aviator&unscoped_q=G_Aviator
All the others don't.

And they shouldn't have semicolons because they'll end up as 
`goggles[] = {"", "G_Spectacles", "G_Aviator";};`

**Comment by xrufix** [comment]
Fixed, thanks for reporting!

**Comment by dedmen** [comment]
No thank you for helping me find and fix armake bugs :D
![amplxe-gui_2018-11-30_10-28-58](https://user-images.githubusercontent.com/3768165/49280625-f6517d80-f48a-11e8-9084-95913cedd79e.png)
Your stuff is perfect for finding performance problems.

**Comment by xrufix** [comment]
No, thank you for providing the community with such a splendid tool ;)
